export const screenGroups: [string, [string, string][]][] = [
  [
    "Onboarding",
    [
      ["M01 · Splash", "/auth/splash"],
      ["M02 · Phone login", "/auth/login"],
      ["M03 · OTP", "/auth/otp"],
      ["M04 · Create profile", "/auth/create-profile"],
      ["M05 · Permissions education", "/auth/permissions"],
    ],
  ],
  [
    "Discover and connect",
    [
      ["M06 · Explore", "/explore"],
      ["M07 · Search", "/search"],
      ["M08 · Filters", "/filters"],
      ["M09 · User profile", "/user/priya"],
      ["M10 · Favorites", "/favorites"],
      ["M11 · Conversations", "/messages"],
      ["M12 · Chat", "/chat/priya"],
      ["M14 · Media viewer", "/media/priya"],
    ],
  ],
  [
    "Audio and video",
    [
      ["M15 · Outgoing audio", "/calls/outgoing/priya?type=audio"],
      ["M15 · Outgoing video", "/calls/outgoing/priya?type=video"],
      ["M16 · Incoming audio", "/calls/incoming/priya"],
      ["M16 · Incoming video", "/calls/incoming/priya?type=video"],
      ["M17 · Audio call", "/calls/audio/priya"],
      ["M18 · Video call", "/calls/video/priya"],
      ["M19 · Call result", "/calls/result/priya"],
      ["M20 · Call history", "/calls"],
      ["M21 · Call details", "/calls/detail/call-1"],
      [
        "M43 · Ongoing call banner (start call then open chat)",
        "/calls/audio/priya",
      ],
    ],
  ],
  [
    "Wallet and Razorpay",
    [
      ["M22 · Wallet", "/wallet"],
      ["M23 · Recharge review", "/wallet/recharge"],
      ["M24 · Razorpay handoff", "/wallet/checkout"],
      ["M25 · Payment results", "/wallet/payment/demo"],
      ["M26 · Transaction history", "/wallet/transactions"],
      ["M27 · Transaction detail", "/wallet/transactions/TX-2401"],
      ["M44 · Balance reminder", "/wallet/low-balance"],
    ],
  ],
  [
    "Account and safety",
    [
      ["M28 · My profile", "/profile"],
      ["M29 · Edit profile", "/profile/edit"],
      ["M30 · Availability", "/profile/availability"],
      ["M31 · Notifications", "/notifications"],
      ["M32 · Settings", "/settings"],
      ["M33 · Privacy", "/settings/privacy"],
      ["M34 · Alert preferences", "/settings/notifications"],
      ["M35 · Blocked users", "/settings/blocked-users"],
      ["M36 · Block confirmation", "/block/priya"],
      ["M37 · Report", "/report/priya"],
      ["M38 · Help", "/settings/help"],
      ["M39 · Policy viewer", "/settings/policies/privacy"],
      ["M40 · Logout", "/settings/logout"],
      ["M41 · Delete account", "/settings/delete-account"],
      ["M42 · Device permission states", "/settings/permissions"],
      ["M46 · Rate call (later)", "/rate/priya"],
    ],
  ],
  [
    "Service states",
    [
      ["M45 · Offline", "/status/offline"],
      ["M45 · Loading", "/status/loading"],
      ["M45 · Error", "/status/error"],
      ["M45 · Maintenance", "/status/maintenance"],
      ["M45 · Required update", "/status/update"],
      ["M45 · Session expired", "/status/expired"],
      ["M45 · Account suspended", "/status/suspended"],
      ["M45 · Unavailable content", "/status/unavailable"],
    ],
  ],
  [
    "Admin · best on desktop web",
    [
      ["A01 · Admin login", "/admin/login"],
      ["A02 · Overview", "/admin"],
      ["A03 · Users", "/admin/users"],
      ["A04 · User detail", "/admin/users/priya"],
      ["A05 · Reports", "/admin/reports"],
      ["A06 · Report detail", "/admin/reports/R-1"],
      ["A07 · Call metadata", "/admin/calls"],
      ["A08 · Payments", "/admin/payments"],
      ["A09 · Payment detail", "/admin/payments/demo-1"],
      ["A10 · Wallet ledger", "/admin/wallets/priya"],
      ["A11 · Pricing", "/admin/pricing"],
      ["A12 · App settings", "/admin/settings"],
      ["A13 · Announcements", "/admin/announcements"],
      ["A14 · Analytics", "/admin/analytics"],
      ["A15 · Audit", "/admin/audit"],
      ["A16 · Reconciliation", "/admin/reconciliation"],
    ],
  ],
];
